service: banter-deepspeech
org: banter
app: banter-deepspeech

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

functions:
  infer:
    handler: infer.inferHandler
    timeout: 30
    events:
      - http:
          path: infer
          method: post
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    zip: true